Fix reference error for certain fonts
foliojs/fontkit pull request #286
Opened 2022-07-07 22:29 UTC by fstrube

Fixes #282.

This branch fixes a ReferenceError that gets thrown when parsing certain fonts, including the Playfair Display font that is in the fontkit repository. The error started happening when version 1.9.0 of fontkit was released.

```
     ReferenceError: Cannot access 'c3x' before initialization
```

The fix involved refactoring the `parse()` function to use block-scoping inside the switch case statements in that function. See [the MDN docs on redeclarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#redeclarations).

2022-07-08 14:56 UTC, Pomax commented
It might make sense to preallocate all the variables outside the switch, as that would have been the effective behaviour when babel transpiled to `var` (due to hoisting) anyway.

2022-07-12 05:13 UTC, fstrube commented
@Pomax @blikblum I preallocated all the variables outside the switch as you suggested. The diff is much smaller, which is nice.

2022-07-12 22:42 UTC, Pomax commented on src/glyph/CFFGlyph.js
> +                var p = stream.pos;
`var` get hoisted, so definitely want to keep these `let` (obeying block scope)

2022-07-12 22:44 UTC, Pomax commented on src/glyph/CFFGlyph.js
> +                var p = stream.pos;
these will want to stay `let` as well

2022-07-12 22:44 UTC, Pomax requested changes
I don't have PR merging powers, but happy to review.

2022-07-13 05:05 UTC, fstrube commented
Thanks for reviewing @Pomax! I made those two changes that you suggested.

There are also a few more instances of `var` declarations in that function. 

* [Line 474](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L474)
* [Line 484](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L484)
* [Line 585](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L585)
* [Line 588](https://github.com/fstrube/fontkit/blob/9b0956a8d733d2b61c27da733cdbd257b7ef8c67/src/glyph/CFFGlyph.js#L588)

Do you think it is worth changing them to `let`? Or should we leave them as is to avoid any unexpected behavior?

2022-07-13 22:37 UTC, Pomax commented
Any opportunity to move from scope-hoisting to block scoped vars is a good opportunity I'd say, but I'll let @devongovett decide whether that's something he would like to see in this PR.

2022-07-19 19:55 UTC, fstrube commented
Hi @devongovett, would you mind taking a look at this? It is causing most of our pdfkit projects that rely on OTF fonts to fail. I'm hoping we can get this merged in soon, then get https://github.com/foliojs/pdfkit/pull/1367 updated and merged as well.

2022-07-24 02:54 UTC, devongovett approved these changes
Thanks!

2022-07-24 02:54 UTC, merged

2023-03-23 19:02 UTC, AlainGourves commented
It is possible to make a new release with this PR ?
The latest version is 2.0.2, released on June 19 2022 before this PR, so the error 

```
ReferenceError: Cannot access 'c3x' before initialization
```
still occurs (for example with the font `PlayfairDisplay-Regular.otf` found in `/test/data/PlayfairDisplay`).

Thanks in advance!